### ISSUE TITLE
Doesn't work when the baseURL contains a path (BaseURLにパスが含まれるときにうまく動かないようです)

### ISSUE THREAD

**Issue by assout** [kenzo0107/backlog#32]
Thank you for the nice library.
In the enterprise version of Backlog, it doesn't seem to work when the BaseURL contains the path.
e.g. http://hoge.backlog.com/backlog/api/v2/issues

ナイスライブラリをありがとうございます。
エンタープライズ版Backlogで、BaseURLにパスが含まれるときにうまく動かないようです。
たとえば、http://hoge.backlog.com/backlog/api/v2/issues などのときです。

**Comment by kenzo0107** [comment]
Thank you for your action.
I haven't considered the enterprise version of Backlog. I've used the ASP version only 😅 
I review your PR.

あなたの行動に感謝します。
エンタープライズ版 Backlog については考慮しておりませんでした。ASP 版しか使ったことがなく 😅 
作成いただいた PR レビューします。
