### ISSUE TITLE
[Feature Request] Use custom fields when creating and updating (ISSUE追加・更新時のカスタムフィールド指定)

### ISSUE THREAD

**Issue by assout** [kenzo0107/backlog#34]
ISSUE追加・更新時のカスタムフィールド指定に対応する予定はありますでしょうか？

**Comment by kenzo0107** [comment]
現状直ちに対応する予定はないです。
理由としては特にカスタムフィールドを利用しておらず、急務ではない為です。（個人的理由ですいません 💦 ）
もしご対応いただけるのであれば大変助かります！

**Comment by assout** [comment]
コメントありがとうございます！
そもそもbacklog APIのカスタムフィールドのパラメータ指定方法がちょっと特殊ですね。。
こちらのユースケースではカスタムフィールドが必須属性なことがあり、うまく対応できそうだったらprさせていただきます。

**Comment by kenzo0107** [comment]
> そもそもbacklog APIのカスタムフィールドのパラメータ指定方法がちょっと特殊ですね。。

特殊ですね 😅 

<img width="572" alt="スクリーンショット 2020-12-27 9 49 53" src="https://user-images.githubusercontent.com/6197906/103161680-e0a91080-4828-11eb-9a54-8ac1c68f8898.png">

現状の struct の json メタデータを元に POST する値を指定する方式では、扱い辛いですね。

なので、カスタムフィールドを指定可能な API については、C# 版 API にある様な実装が望ましいなと思っています。
https://github.com/hal1932/NBacklog/blob/master/NBacklog/DataTypes/Ticket.cs#L323-L333


## 検討している実装

以下の様な実装できればなと考えました。

ISSUE 追加 API の input に CustomFields 項目を追加する。

ISSUE 追加 API のカスタムフィールドは既に定義している カスタムフィールドの struct とは構成が異なっていたので、 IssueCustomField と定義しています。
https://github.com/kenzo0107/backlog/blob/master/customfield.go

```
// IssueCustomFiled : custom field in issue
type IssueCustomFiled struct {
	ID          *int        `json:"id,omitempty"`
	FieldTypeID *int        `json:"fieldTypeId,omitempty"`
	Name        *string     `json:"name,omitempty"`
	Value       interface{} `json:"value,omitempty"`
}

type CreateIssueInput struct {
	...
	CustomFields    []*IssueCustomFiled
}
```

`url.Values{}` に input とカスタムフィールド指定時に `customField_{id}` の値を指定して POST する。

```
func (c *Client) CreateIssueContext(ctx context.Context, input *CreateIssueInput) (*Issue, error) {
	...
	values := url.Values{}

	for _, v := range input.CustomFields {
		values.Add(fmt.Sprintf("customField_%v", v.ID), v.Value)
	}

	req, err := c.NewRequest("POST", u, values)
```

url.Values{} に input の情報を渡す処理をまだ思いついてません。

そもそも NewRequest() の第３引数は interface{} なので、 url.Values{} でなくとも受け渡しに良いのがあれば、それで良いのかもしれませんね。

**Comment by assout** [comment]
なるほど。当方Go初心者のためご教示いただき勉強になります。ちょっと考えてみます。
