### ISSUE TITLE
課題更新時にintの項目を空(未設定)に更新できない

### ISSUE THREAD

**Issue by assout** [kenzo0107/backlog#40]
以下のint属性の項目について、未設定(クリア)に更新することができないようです。(0を指定するとリテラル0で更新される)
- ResolutionID
- EstimatedHours
- ActualHours
- AssigneeID

※以下はintだが必須属性のため問題なし
- IssueTypeID
- PriorityID

※Backlog API上は値未指定での更新は可能でした。
`assigneeId=` -> 担当者未設定に更新

**Comment by kenzo0107** [comment]
issue 作成ありがとうございます！
未指定にする場合を加味しないといけないですね。

Thank you for creating the issue!
We have to take into account the case of not specifying it.

**Comment by kenzo0107** [comment]
再現しました。

```
func main() {
	apiKey := os.Getenv("API_KEY")
	baseURL := os.Getenv("BASE_URL")
	c := backlog.New(apiKey, baseURL, backlog.OptionDebug(true))

	input := &backlog.UpdateIssueInput{,
		EstimatedHours: backlog.Int(0),
	}
	issue, err := c.UpdateIssue("SRE-602", input)
	if err != nil {
		log.Println(err)
		return
	}
	log.Printf("%#v", *issue.EstimatedHours)
}
```

対策として、以下検証しました。

## 対策1. UpdateIssueInput の EstimatedHours interface{} で扱う

```
type UpdateIssueInput struct {
  EstimatedHours interface{} `json:"estimatedHours,omitempty"`
```

interface{} で扱うことで、以下が可能です。
1. backlog.Int(0) → 0 を指定する
2. backlog.String("") → 未設定にする。

Int, String 双方受け入れるという意図が利用者に伝えられるかと思います。

1. 実装例 0を指定
```
	input := &backlog.UpdateIssueInput{,
		EstimatedHours: backlog.Int(0),
	}
	issue, err := c.UpdateIssue("SRE-602", input)
	...
	fmt.Printf("%#v", *issue.EstimatedHours) # Output: 0
```

2. 実装例 空にする
```
	input := &backlog.UpdateIssueInput{,
		EstimatedHours: backlog.String(""),
	}
	issue, err := c.UpdateIssue("SRE-602", input)
	...
	fmt.Printf("%#v", *issue.EstimatedHours) # Output: ""
```

## 対策2. UpdateIssueInput の EstimatedHours *string で扱う

対策1 に比べ backlog.String に処理を絞っていて、
利用者の選択肢が縛られるので理解はしやすそう。

```
	input := &backlog.UpdateIssueInput{,
		EstimatedHours: backlog.String("0"),
	}
	issue, err := c.UpdateIssue("SRE-602", input)
	...
	fmt.Printf("%#v", *issue.EstimatedHours) # Output: 0
```

だが、`struct Issue` の `EstimatedHours *int` なので *string に絞るのは違和感があり、直感的ではなさそう。

```
type Issue struct {
  EstimatedHours *int                `json:"estimatedHours,omitempty"`
```

## 結論

以上から 対策1 の空指定を許容する為、 `backlog.UpdateIssueInput` では、以下値を `interface{}` で扱うのが良いかと思いました。

* ResolutionID
* EstimatedHours
* ActualHours
* AssigneeID

@assout > ご意見あればよろしくお願い致します :pray:


## 余談1

尚、空値を指定するパターンを examples/issue/issue.go に記載しておけば、利用者に親切かなと思いました。

## 余談2

同値で更新をしようとすると以下エラーが発生することを確認しました。
これはどうやら仕様の様です 😢 

```
code:7 message:No comment content. moreInfo:
```

参考: https://github.com/Shinpeim/BackLogger/issues/23

**Comment by assout** [comment]
@kenzo0107 
ご丁寧にありがとうございます！
対策1なら、利用者目線でも理解しやすいと思います！(コメントないしテストで補足は必要かもですが)

**Comment by kenzo0107** [comment]
@assout ご確認ありがとうございます。

対策1 の修正をします。

> コメントないしテストで補足は必要かもですが

補足します 💪 


さらに余談ですが、

`interface{}` なら指定する際にポインタにする必要もないですね。

空にする
```
input := &backlog.UpdateIssueInput{,
  EstimatedHours: "",
}
```

1 に設定
```
input := &backlog.UpdateIssueInput{,
  EstimatedHours: 1,
}
```

**Comment by kenzo0107** [comment]
@assout こちら対応しました。
https://github.com/kenzo0107/backlog/pull/43

**Comment by assout** [comment]
ありがとうございます！助かります！
